### ISSUE TITLE
Could we get indexed image ?

### ISSUE THREAD

**Issue by huangjinshe** [thomas694/WebPAnimationViewer#1]
Maybe directly save as indexed png-8. it would be really good for performance.

**Comment by thomas694** [comment]
What do you try to accomplish?
Which data do you want to save as "indexed png-8" and why? A WebP can be more than 8 bit color depth.
Where is performance a problem? Do you have a real-world example (by email, if not suitable here)?

**Comment by huangjinshe** [comment]
I want to get every frame original byte data to my memory (not after decoded), I believe in that case it won't use that much memory. 
the reason that I want to do that: once I decoded it, I need to use more memory to save all animation as true color, but I want to save the original byte array to memory, and then decode every frame one by one when I need, just like real time play it. (earlier I thinked about use indexed image after decode, but as I said it's not possible). could you provide that api for us? thanks.

**Comment by huangjinshe** [comment]
it would be very helpful if you could share the new version of libwebpdemux which you modified.

**Comment by thomas694** [comment]
You can check out the new version of the [wrapper library](https://github.com/thomas694/WebP-wrapper-animatedWebP) to see if it meets your needs.
